# Generated by Django 5.2.3 on 2025-06-16 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_curio_created_at_alter_curio_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True},
        ),
    ]
