# Generated by Django 5.2.3 on 2025-06-17 13:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('other', 'Other')], default='other', max_length=20)),
                ('platform_video_id', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True)),
                ('url', models.TextField()),
                ('thumbnail_url', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.profile')),
                ('curio', models.ForeignKey(blank=True, db_column='curio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.curio')),
            ],
            options={
                'db_table': 'clips',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClipProcessingTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clip', models.ForeignKey(db_column='clip_id', on_delete=django.db.models.deletion.CASCADE, to='api.clip')),
            ],
            options={
                'db_table': 'clip_processing_task',
                'managed': True,
            },
        ),
    ]
