# Generated by Django 5.2.3 on 2025-06-17 13:56

from django.db import migrations, models
from django.contrib.postgres.fields import ArrayField


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20250617_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='embeddings',
            field=ArrayField(
                base_field=models.FloatField(),
                size=1536,
                blank=True,
                null=True,
                help_text='OpenAI embeddings vector (1536 dimensions)'
            ),
        ),
    ]
