# Generated by Django 5.2.3 on 2025-06-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20250617_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
