# Generated by Django 5.2.3 on 2025-06-17 13:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20250617_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='embeddings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=1536),
        ),
    ]
