# Generated by Django 5.2.3 on 2025-06-17 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20250617_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
