# Generated by Django 5.2.3 on 2025-06-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20250617_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
