# Generated by Django 5.2.3 on 2025-06-18 11:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_clip_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipEmbedding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=20)),
                ('chunk_index', models.IntegerField(null=True)),
                ('text_chunk', models.TextField()),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clip', models.ForeignKey(db_column='clip_id', on_delete=django.db.models.deletion.CASCADE, to='api.clip')),
            ],
            options={
                'db_table': 'clip_embeddings',
                'managed': True,
                'indexes': [models.Index(fields=['clip_id'], name='clip_embedd_clip_id_fc35e6_idx'), models.Index(fields=['field'], name='clip_embedd_field_cff153_idx')],
            },
        ),
    ]
